version: '3.4'

services:

  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=leotarla
      - TZ=America/Sao_Paulo
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    hostname: postgres

  gutendex:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/api/v1/health"
        ]
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 30s
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    hostname: gutendex
    volumes:
      - ./src:/home/root/gutendex/src/

volumes:
  postgres:
  gutendex:
